name: deploy
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make zip
        run: |
          mkdir output
          zip -r output/release.zip . -x .git/\* -x .github/\* -x output/\*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/release.zip
          asset_name: SEECHAK-SDK-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Trigger VPM repository workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: seechak
          repo: vpm
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: build-listing.yml
          ref: main
          trigger_workflow: true
          wait_workflow: true